//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class adminreport
    {
        public int reportid { get; set; }
        public Nullable<int> reporttypeid { get; set; }
        public string reportname { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> isfordm { get; set; }
        public Nullable<bool> isforpsr { get; set; }
        public Nullable<bool> isforsm { get; set; }
        public Nullable<bool> cancustomizereceiver { get; set; }
        public Nullable<int> reportorder { get; set; }
    }
}
