//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class approvaltree
    {
        public long approvaltreeid { get; set; }
        public Nullable<int> moduleid { get; set; }
        public Nullable<long> employeeid { get; set; }
        public Nullable<int> treelevel { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<long> districtmanagerid { get; set; }
    
        public virtual module module { get; set; }
        public virtual employee employee { get; set; }
    }
}
