//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class attendee
    {
        public long attendeeid { get; set; }
        public Nullable<long> practivityid { get; set; }
        public long doc_id { get; set; }
        public string doc_name { get; set; }
        public string remarks { get; set; }
        public string specialization { get; set; }
    
        public virtual practivity practivity { get; set; }
    }
}
