//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public branch()
        {
            this.employees = new HashSet<employee>();
            this.warehouses = new HashSet<warehouse>();
            this.suppliers = new HashSet<supplier>();
        }
    
        public long branchid { get; set; }
        public string branchcode { get; set; }
        public string branchname { get; set; }
        public string branchaddress { get; set; }
        public string telephone { get; set; }
        public string proprietor { get; set; }
        public string tinno { get; set; }
        public Nullable<long> defaultwarehouseid { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> isdefault { get; set; }
        public Nullable<long> createdbyid { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<long> updatebyid { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public Nullable<bool> syncstatus { get; set; }
        public Nullable<System.DateTime> syncdate { get; set; }
        public Nullable<short> branchtype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouse> warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier> suppliers { get; set; }
    }
}
