//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class callnote
    {
        public long call_note_id { get; set; }
        public long call_id { get; set; }
        public int call_note_type_id { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> note_timestamp { get; set; }
    
        public virtual call call { get; set; }
        public virtual jointcall jointcall { get; set; }
    }
}
