//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class callevalnote
    {
        public long callevalnoteid { get; set; }
        public Nullable<long> call_id { get; set; }
        public Nullable<int> evaltypeid { get; set; }
        public string notes { get; set; }
    
        public virtual jointcall jointcall { get; set; }
        public virtual evaluationtype evaluationtype { get; set; }
    }
}
