//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class call
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public call()
        {
            this.signatures = new HashSet<signature>();
            this.callnotes = new HashSet<callnote>();
        }
    
        public long call_id { get; set; }
        public Nullable<long> inst_doc_id { get; set; }
        public Nullable<int> cycle_day_id { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<bool> planned { get; set; }
        public Nullable<bool> makeup { get; set; }
        public Nullable<System.DateTime> start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<int> reschedule_day_id { get; set; }
        public Nullable<int> signed_day_id { get; set; }
        public Nullable<int> retry_count { get; set; }
        public Nullable<bool> joint_call { get; set; }
        public Nullable<bool> quick_sign { get; set; }
        public Nullable<System.DateTime> location_datetime { get; set; }
        public Nullable<long> createdbyid { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<long> updatedbyid { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual institutiondoctormap institutiondoctormap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<signature> signatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<callnote> callnotes { get; set; }
    }
}
