//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class cycleday
    {
        public int cycle_day_id { get; set; }
        public Nullable<int> cycle_set_id { get; set; }
        public Nullable<int> cycle_number { get; set; }
        public Nullable<int> day_number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string date_type_id { get; set; }
        public string label { get; set; }
    
        public virtual cycleset cycleset { get; set; }
    }
}
