//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class evaluationtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evaluationtype()
        {
            this.callevalnotes = new HashSet<callevalnote>();
        }
    
        public int evaltypeid { get; set; }
        public string evaltypecode { get; set; }
        public string evaltypename { get; set; }
        public Nullable<int> evaltypepriority { get; set; }
        public Nullable<decimal> evaltypeweight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<callevalnote> callevalnotes { get; set; }
    }
}
