//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class expensereportdetail
    {
        public long expensereportdetailid { get; set; }
        public Nullable<long> expensereportid { get; set; }
        public Nullable<int> dayno { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string route { get; set; }
        public string workwith { get; set; }
        public Nullable<int> transpotypeid { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> meals { get; set; }
        public Nullable<decimal> miscellaneous { get; set; }
        public Nullable<decimal> totaldaily { get; set; }
        public Nullable<int> personal { get; set; }
        public Nullable<long> totalkm { get; set; }
        public Nullable<int> business { get; set; }
        public string imgloc { get; set; }
    
        public virtual expensereport expensereport { get; set; }
        public virtual transportationtype transportationtype { get; set; }
    }
}
