//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class fundliquidation
    {
        public long fundliquidationid { get; set; }
        public Nullable<long> warehouseid { get; set; }
        public Nullable<int> moduleid { get; set; }
        public Nullable<long> requestid { get; set; }
        public Nullable<System.DateTime> datesubmitted { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public Nullable<System.DateTime> actualdate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string receiptimagepath { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> endorsedto { get; set; }
        public string remarks { get; set; }
    
        public virtual warehouse warehouse { get; set; }
    }
}
