//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class fundrequest
    {
        public long fundrequestid { get; set; }
        public Nullable<long> warehouseid { get; set; }
        public Nullable<int> moduleid { get; set; }
        public Nullable<long> requestid { get; set; }
        public Nullable<System.DateTime> daterequested { get; set; }
        public Nullable<System.DateTime> dateneeded { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> paymentmode { get; set; }
        public string paymentref { get; set; }
        public Nullable<long> endorsedto { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isdisburse { get; set; }
        public string disbursementref { get; set; }
        public string disbursementremarks { get; set; }
        public Nullable<System.DateTime> disbursementdate { get; set; }
    
        public virtual warehouse warehouse { get; set; }
    }
}
