//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class institution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public institution()
        {
            this.institutiondoctormaps = new HashSet<institutiondoctormap>();
            this.practivities = new HashSet<practivity>();
        }
    
        public int inst_id { get; set; }
        public string inst_code { get; set; }
        public string inst_name { get; set; }
        public string inst_location { get; set; }
        public Nullable<long> warehouseid { get; set; }
        public Nullable<long> area_id { get; set; }
        public Nullable<long> createdbyid { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<long> updatedbyid { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> isattendance { get; set; }
        public Nullable<int> insttypeid { get; set; }
        public string contactperson { get; set; }
        public string contactdetails { get; set; }
        public string owner { get; set; }
        public Nullable<int> noofoutlets { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<institutiondoctormap> institutiondoctormaps { get; set; }
        public virtual institutiontype institutiontype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<practivity> practivities { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
