//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class plan
    {
        public long plan_id { get; set; }
        public Nullable<int> cycle_set_id { get; set; }
        public Nullable<int> cycle_number { get; set; }
        public Nullable<int> warehouseid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<int> createdbyid { get; set; }
        public Nullable<int> updatedbyid { get; set; }
    }
}
