//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class plandetail
    {
        public long plan_detail_id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public Nullable<long> inst_doc_id { get; set; }
        public Nullable<int> cycle_day_id { get; set; }
        public string label { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
