//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class practivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public practivity()
        {
            this.attendees = new HashSet<attendee>();
            this.practivitybudgets = new HashSet<practivitybudget>();
            this.practivityoutcomes = new HashSet<practivityoutcome>();
        }
    
        public long practivityid { get; set; }
        public Nullable<long> warehouseid { get; set; }
        public Nullable<int> activityid { get; set; }
        public Nullable<int> inst_id { get; set; }
        public Nullable<int> doc_id { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> activitydate { get; set; }
        public Nullable<decimal> totalbudget { get; set; }
        public string remarks { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> endorsedto { get; set; }
        public Nullable<int> statusacc { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
    
        public virtual activity activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendee> attendees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<practivitybudget> practivitybudgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<practivityoutcome> practivityoutcomes { get; set; }
        public virtual institution institution { get; set; }
        public virtual doctor doctor { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
