//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.practivityoutcomes = new HashSet<practivityoutcome>();
            this.tieupproducts = new HashSet<tieupproduct>();
            this.receivings = new HashSet<receiving>();
        }
    
        public int product_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string itemcatcode { get; set; }
        public Nullable<long> createdbyid { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<long> updatedbyid { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<int> itemtypeid { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> pinmoney { get; set; }
        public Nullable<int> packagingcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<practivityoutcome> practivityoutcomes { get; set; }
        public virtual itemcategory itemcategory { get; set; }
        public virtual packaging packaging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tieupproduct> tieupproducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receiving> receivings { get; set; }
    }
}
