//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class receiving
    {
        public long receivingid { get; set; }
        public Nullable<int> warehouseid { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> material_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> datereceived { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual product product { get; set; }
        public virtual material material { get; set; }
    }
}
