//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class rescheduledcall
    {
        public long rescheduled_call_id { get; set; }
        public long call_id { get; set; }
        public int cycle_day_id { get; set; }
        public int reason_id { get; set; }
        public string remarks { get; set; }
        public bool sent { get; set; }
    }
}
