//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class salaryloan
    {
        public long salaryloanid { get; set; }
        public Nullable<long> employeeid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<decimal> deduction { get; set; }
        public string purpose { get; set; }
        public Nullable<long> createdbyid { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<long> updatedbyid { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> endorsedto { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
