//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class statustrail
    {
        public long trailid { get; set; }
        public Nullable<int> moduleid { get; set; }
        public Nullable<long> requestid { get; set; }
        public Nullable<int> statusid { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> traildate { get; set; }
        public Nullable<long> employeeid { get; set; }
        public Nullable<int> treelevel { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
