//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tieupproduct
    {
        public long tieupproductid { get; set; }
        public Nullable<long> tieupid { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> monthlyqty { get; set; }
        public Nullable<decimal> rebate { get; set; }
        public Nullable<decimal> pinmoney { get; set; }
    
        public virtual tieup tieup { get; set; }
        public virtual product product { get; set; }
    }
}
