//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tieup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tieup()
        {
            this.tieupproducts = new HashSet<tieupproduct>();
        }
    
        public long tieupid { get; set; }
        public Nullable<long> warehouseid { get; set; }
        public Nullable<int> tieupclass { get; set; }
        public Nullable<int> producttype { get; set; }
        public Nullable<long> inst_id { get; set; }
        public Nullable<long> doc_id { get; set; }
        public Nullable<int> tieupmode { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> startmonth { get; set; }
        public Nullable<int> dealtype { get; set; }
        public Nullable<int> tieuptype { get; set; }
        public string tradeoutlet { get; set; }
        public string hospitalpharmacy { get; set; }
        public string notes { get; set; }
        public string otherpromooffers { get; set; }
        public Nullable<bool> haspinmoney { get; set; }
        public Nullable<decimal> rebatediscount { get; set; }
        public Nullable<decimal> totalmonthlyincome { get; set; }
        public Nullable<decimal> totalmonthlyrebates { get; set; }
        public Nullable<decimal> totalmonthlypin { get; set; }
        public string rebatenotes { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<long> endorsedto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tieupproduct> tieupproducts { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
