//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class userlog
    {
        public long logid { get; set; }
        public Nullable<long> referenceno { get; set; }
        public Nullable<int> typeid { get; set; }
        public string module { get; set; }
        public Nullable<System.DateTime> logdate { get; set; }
        public string action { get; set; }
        public string username { get; set; }
    }
}
