//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class useraccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public useraccount()
        {
            this.userprivs = new HashSet<userpriv>();
            this.usersubprivs = new HashSet<usersubpriv>();
        }
    
        public long useraccountid { get; set; }
        public string usercode { get; set; }
        public Nullable<long> employeeid { get; set; }
        public string username { get; set; }
        public string userpass { get; set; }
        public Nullable<bool> isappsysadmin { get; set; }
        public byte[] usersign { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> createdbyid { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> updatedbyid { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public Nullable<int> showwhatsnew { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userpriv> userprivs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usersubpriv> usersubprivs { get; set; }
    }
}
