//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class usersubpriv
    {
        public long usersubprivno { get; set; }
        public long useraccountid { get; set; }
        public Nullable<int> submodcode { get; set; }
        public Nullable<bool> canaccess { get; set; }
    
        public virtual useraccount useraccount { get; set; }
        public virtual systemsubmodule systemsubmodule { get; set; }
    }
}
