//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class userpriv
    {
        public long userprivno { get; set; }
        public long useraccountid { get; set; }
        public int modcode { get; set; }
        public Nullable<bool> canrequest { get; set; }
        public Nullable<bool> canadd { get; set; }
        public Nullable<bool> canedit { get; set; }
    
        public virtual useraccount useraccount { get; set; }
        public virtual module module { get; set; }
    }
}
