//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class vehiclerepair
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehiclerepair()
        {
            this.vehiclerepairdetails = new HashSet<vehiclerepairdetail>();
        }
    
        public long vehiclerepairid { get; set; }
        public Nullable<long> warehouseid { get; set; }
        public Nullable<long> vehicleid { get; set; }
        public Nullable<System.DateTime> datefiled { get; set; }
        public Nullable<long> odo { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> endorsedto { get; set; }
        public Nullable<decimal> avgamount { get; set; }
        public Nullable<long> supplierno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiclerepairdetail> vehiclerepairdetails { get; set; }
        public virtual warehouse warehouse { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
