//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFFO.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class vehiclerepairdetail
    {
        public long vehiclerepairdetailid { get; set; }
        public Nullable<long> vehiclerepairid { get; set; }
        public Nullable<long> supplierno { get; set; }
        public string particulars { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public string rowuuid { get; set; }
    
        public virtual supplier supplier { get; set; }
        public virtual vehiclerepair vehiclerepair { get; set; }
    }
}
