//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SimpleFFO.FFOPettyCashWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Generate_TokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback Download_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Upload_DataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::SimpleFFO.Properties.Settings.Default.SimpleFFO_FFOPettyCashWS_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Generate_TokenCompletedEventHandler Generate_TokenCompleted;
        
        /// <remarks/>
        public event Download_DataCompletedEventHandler Download_DataCompleted;
        
        /// <remarks/>
        public event Upload_DataCompletedEventHandler Upload_DataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Generate_Token", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Generate_Token(long employeeid) {
            object[] results = this.Invoke("Generate_Token", new object[] {
                        employeeid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Generate_TokenAsync(long employeeid) {
            this.Generate_TokenAsync(employeeid, null);
        }
        
        /// <remarks/>
        public void Generate_TokenAsync(long employeeid, object userState) {
            if ((this.Generate_TokenOperationCompleted == null)) {
                this.Generate_TokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerate_TokenOperationCompleted);
            }
            this.InvokeAsync("Generate_Token", new object[] {
                        employeeid}, this.Generate_TokenOperationCompleted, userState);
        }
        
        private void OnGenerate_TokenOperationCompleted(object arg) {
            if ((this.Generate_TokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Generate_TokenCompleted(this, new Generate_TokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Download_Data", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Download_Data(string rtoken, myTransactCode code, string branchid) {
            object[] results = this.Invoke("Download_Data", new object[] {
                        rtoken,
                        code,
                        branchid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Download_DataAsync(string rtoken, myTransactCode code, string branchid) {
            this.Download_DataAsync(rtoken, code, branchid, null);
        }
        
        /// <remarks/>
        public void Download_DataAsync(string rtoken, myTransactCode code, string branchid, object userState) {
            if ((this.Download_DataOperationCompleted == null)) {
                this.Download_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownload_DataOperationCompleted);
            }
            this.InvokeAsync("Download_Data", new object[] {
                        rtoken,
                        code,
                        branchid}, this.Download_DataOperationCompleted, userState);
        }
        
        private void OnDownload_DataOperationCompleted(object arg) {
            if ((this.Download_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Download_DataCompleted(this, new Download_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Upload_Data", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Upload_Data(string rtoken, myTransactCode code, string jsondata) {
            object[] results = this.Invoke("Upload_Data", new object[] {
                        rtoken,
                        code,
                        jsondata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Upload_DataAsync(string rtoken, myTransactCode code, string jsondata) {
            this.Upload_DataAsync(rtoken, code, jsondata, null);
        }
        
        /// <remarks/>
        public void Upload_DataAsync(string rtoken, myTransactCode code, string jsondata, object userState) {
            if ((this.Upload_DataOperationCompleted == null)) {
                this.Upload_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpload_DataOperationCompleted);
            }
            this.InvokeAsync("Upload_Data", new object[] {
                        rtoken,
                        code,
                        jsondata}, this.Upload_DataOperationCompleted, userState);
        }
        
        private void OnUpload_DataOperationCompleted(object arg) {
            if ((this.Upload_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Upload_DataCompleted(this, new Upload_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum myTransactCode {
        
        /// <remarks/>
        CGetEmployees,
        
        /// <remarks/>
        CGetExpenseType,
        
        /// <remarks/>
        CGetFundType,
        
        /// <remarks/>
        CGetVendor,
        
        /// <remarks/>
        CGetBranch,
        
        /// <remarks/>
        CGetVendorCategory,
        
        /// <remarks/>
        CPostFundReleased,
        
        /// <remarks/>
        CPostFundLiquidation,
        
        /// <remarks/>
        CPostExpenseType,
        
        /// <remarks/>
        CPostVendor,
        
        /// <remarks/>
        CPostExpenseReport,
        
        /// <remarks/>
        CPostFundReleasedCashTransfer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Generate_TokenCompletedEventHandler(object sender, Generate_TokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Generate_TokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Generate_TokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Download_DataCompletedEventHandler(object sender, Download_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Download_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Download_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Upload_DataCompletedEventHandler(object sender, Upload_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Upload_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Upload_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591